accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path


from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

accounts/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime

from django.db import models

from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import SignUpForm
# Create your views here.

def signup(request):
    if request.method=="POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_passkey = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_passkey)
            login(request, user)
            return redirect('../../polls')
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})

polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        return Question.objects.filter( pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

def detail(request, questionid):
    try:
        question = Question.objects.get(pk=questionid)
    except Question.DoesNotExist:
        raise Http404("Question Doesn't exist")
    choice = question.choice_set.all()
    template = loader.get_template('polls/detail.html') 
    return HttpResponse(template.render({'question': question, 'choice': choice}, request))

class DetailView(LoginRequiredMixin, generic.DetailView): 
    login_url='../../accounts/login'
    redirect_field_name = 'next'
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/result.html', {'question': question})


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/result.html'

@login_required(login_url='../../../accounts/login/')
def vote(request, question_id):
    if request.user.is_authenticated:
        pass
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'choice': question.choice_set.all(),
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}SignUp{% endblock %}
{% block content %}
    <h2>SignUP</h2>
    <form method='post'>
    {% csrf_token %}
    {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
                <small style='color: grey'>{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
        </p>
    {% endfor %}
    <button type="submit">SignUp</button>
    <form>
{% endblock %}

polls/templates/polls/detail.html
{% if user.is_authenticated %}
<p>Hi, {{ user.first_name }}</p>
<a href="{% url 'logout' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}">Login</a>
{% endif %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action = "{% url 'polls:vote' question.id%}" method="post">
{% csrf_token %}
    {% for q in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ q.id }}">
        <label for="choice{{ forloop.counter }}">{{ q.choice_text }}</label><br>
    {% endfor %}
        <input type="submit" value="vote">
</form>
<a href="{% url 'accounts:signup' %}">SignUp Here</a>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{%if user.is_authenticated %}
<p>Hi, {{ user.first_name }}</p>
<a href="{% url 'logout' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}">Login</a>
{% endif %}
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No Polls are Available.</p>
{% endif %}
<a href="{% url 'accounts:signup' %}">SignUp Here</a>

polls/templates/polls/result.html
{%if user.is_authenticated %}
<p>Hi, {{ user.first_name }}</p>
<a href="{% url 'logout' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}">Login</a>
{% endif %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
{% with vote=choice.votes %}
    <li>{{ choice.choice_text }} -- {{ vote }} vote{{vote|pluralize }}</li>
{% endwith %}
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<a href="{% url 'accounts:signup' %}">SignUp Here</a>
<a href="{% url 'polls:index' %}">Home</a>

templates/base.html
<!DOCTYPE HTML>
<html>
<head>
    <title>{% block title %}Django{% endblock %}</title>
</head>
<body>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>